from datetime import datetime
from typing import List, Optional, Any

from src.layer2_theory.market_state import MarketTheoryState
from src.layer3_strategy.models import OrderIntent

class PipelineContext:
    """
    State object passed sequentially through Rule Engine modules.
    Modules mutate this context to collaboratively build Order Intents.
    """
    def __init__(self, theory_state: MarketTheoryState, timestamp: datetime):
        self.theory_state = theory_state
        self.timestamp = timestamp
        
        # Collaborative variables set by modules
        self.active_polarity_is_bullish: Optional[bool] = None
        
        # Trackers that passed the pre-setup / trigger conditions
        self.setup_candidates: List[Any] = []
        
        # The final output generated by formatting modules
        self.intents: List[OrderIntent] = []
